version: '3.8'
services:
  server:
    container_name: grpc-server
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    restart: always
    depends_on:
      - db
  client:
    container_name: grpc-client
    build: ./client
    ports:
      - "8081:8081"
    volumes:
      - ./client:/app
    restart: always
    depends_on:
      - server
      - db
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    restart: always
    container_name: grpc-database
